version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      # /volumes/etcd будет создана в текущей директории, если переменная не определена
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - default

  minio:
    container_name: milvus-minio
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      # /volumes/minio будет создана в текущей директории, если переменная не определена
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    ports:
      - "9000:9000"
      - "9001:9001"  # Web UI MinIO
    command: minio server /minio_data --console-address ":9001"
    networks:
      - default

  # Attu GUI for Milvus management
  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.2.8
    ports:
      - "8000:3000"
    environment:
      MILVUS_URL: standalone:19530
    networks:
      - default

  # Milvus vector database service
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: launchpad-bucket
    volumes:
      # /volumes/milvus будет создана в текущей директории, если переменная не определена
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      etcd:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - default

networks:
  default:
    driver: bridge
    external: true
    name: "launchpad_network"
